version: '1'

services:

  djangoapp:

    image: my-djangoapp-image

    container_name: djangoapp-container

    ports:

      - "8001:8000"

    environment:

      - PG_USER=postgres

      - PG_PASSWORD=postgres

      - PG_DB=postgres

      - PG_HOST=db

      - PG_PORT=5432

    depends_on:

      - db

    restart: always

 

  db:

    image: postgres:12

    container_name: db-container

    ports:

      - "5432:5432"

    environment:

      - POSTGRES_USER=postgres

      - POSTGRES_PASSWORD=postgres

      - POSTGRES_DB=postgres

    volumes:

      - pgdata:/var/lib/postgresql/data

volumes:

  pgdata:
